-- Crear la tabla OWNER
CREATE TABLE OWNER (
    ID BINARY(16) NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME DEFAULT NULL,
    AVATAR VARCHAR(255) DEFAULT NULL
);

-- Crear la tabla PET
CREATE TABLE PET (
    ID BINARY(16) NOT NULL PRIMARY KEY,
    OWNER_ID BINARY(16),
    NAME VARCHAR(255) NOT NULL,
    BREED VARCHAR(255),
    GENDER VARCHAR(255) NOT NULL,
    DATE_BIRTH DATE NOT NULL,
    DATE_ADOPTION DATE,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    PHOTO VARCHAR(255),
    DATE_DISABLE DATE,
    FOREIGN KEY (OWNER_ID) REFERENCES OWNER(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Crear la tabla MEDICINE
CREATE TABLE MEDICINE (
    ID BINARY(16) NOT NULL PRIMARY KEY,
    PET_ID BINARY(16),
    NAME VARCHAR(255) NOT NULL,
    DOSE VARCHAR(255) NOT NULL,
    FREQUENCY VARCHAR(255) NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    VET_NAME VARCHAR(255),
    NOTES TEXT
    FOREIGN KEY (PET_ID) REFERENCES PET(ID) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Crear la tabla VISIT
CREATE TABLE VISIT (
    ID BINARY(16) NOT NULL PRIMARY KEY,
    PET_ID BINARY(16),
    VET_NAME VARCHAR(255),
    DATE_VISIT DATE NOT NULL,
    DIAGNOSIS TEXT,
    FILE VARCHAR(255),
    FOREIGN KEY (PET_ID) REFERENCES PET(ID) ON DELETE CASCADE ON UPDATE CASCADE
);